/**
 * Copy right by Persistent PVT LTD.
 */
package com.psl.controller;

import java.io.IOException;

import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

import org.apache.commons.httpclient.Header;
import org.apache.commons.httpclient.HttpClient;
import org.apache.commons.httpclient.methods.GetMethod;
import org.apache.commons.httpclient.methods.PostMethod;
import org.json.JSONObject;

import com.psl.model.GitHubUser;
import com.psl.service.GitHubAuthenticationService;
import com.psl.service.GitHubAuthenticationServiceImpl;

/**
 * @author Praveen GK
 *
 */
public class GitHubAuthenticationController {

	// GitHub access token URL
	final private String URL = "https://github.com/login/oauth/access_token";
	// GitHub client Id
	final private String clientId = "13a5bec734f0b4f91435";
	//GitHub Secret code
	final private String clientSecret = "ff00139c8507f5a49180ffd9726258cff6589412";
	//GitHub given redirect URL
	final private String redirectURL = "http://localhost:9090/EclipsePluginCXF/rest/Outh/authentication";

	
	
	/**
	 * This method is used to get access token of GitHub user.
	 * @param code This parameter is unique for every request and generated by GitHub server
	 * @return It returns JSON format of GitHub user information
	 */
	@GET
	@Path("/Outh/authentication")
	@Consumes("text/plain")
	@Produces("application/json")
	public Response gitHubAuthenticationCode(@QueryParam("code") String code) {
		HttpClient httpClient = new HttpClient();
		PostMethod postMethod = new PostMethod(URL);
		postMethod.addParameter("client_id", clientId);
		postMethod.addParameter("client_secret", clientSecret);
		postMethod.addParameter("code", code);
		postMethod.addParameter("redirect_uri", redirectURL);
		Header header = new Header();
		header.setName("content-type");
		header.setValue("application/x-www-form-urlencoded");
		header.setName("accept");
		header.setValue("application/json");
		postMethod.addRequestHeader(header);
		String responseOutput = null;
		try {
			httpClient.executeMethod(postMethod);
			responseOutput = postMethod.getResponseBodyAsString();
		} catch (IOException e) {
			e.printStackTrace();
		}
		if (postMethod.getStatusCode() != 200) {
			throw new RuntimeException("Failed : HTTP error code : "
					+ postMethod.getStatusCode());
		}
		JSONObject jsonObject = new JSONObject(responseOutput);
		return getGitHubUserDetails((String) jsonObject
				.get("access_token"));
	}

	/**
	 * This method is used to get GitHub user information by using of API 
	 * and access token.Here we used Get request to get user details
	 * @param accessToken Its unique per user.
	 * @return It returns JSON format of GitHub user informations
	 */
	public Response getGitHubUserDetails(String accessToken) {
		HttpClient httpClient = new HttpClient();
		GetMethod getMethod = new GetMethod(
				"https://api.github.com/user?access_token=" + accessToken);
		String responseOutput = null;
		try {
			httpClient.executeMethod(getMethod);
			responseOutput = getMethod.getResponseBodyAsString();
		} catch (IOException e) {
			e.printStackTrace();
		}
		GitHubUser gitHubUser = new GitHubUser();
		JSONObject jsonObject = new JSONObject(responseOutput);
		gitHubUser.setUserName(jsonObject.get("login").toString());
		gitHubUser.setGithubId(jsonObject.get("id").toString());
		gitHubUser.setGithubURL(jsonObject.get("url").toString());
		gitHubUser.setAccessToken(accessToken);
		if (jsonObject.get("email") != null) {
			gitHubUser.setEmail(jsonObject.get("email").toString());
		}
		if (jsonObject.get("name") != null) {
			gitHubUser.setGithubName(jsonObject.get("name").toString());
		}
		if (jsonObject.get("location") != null) {
			gitHubUser.setLocation(jsonObject.get("location").toString());
		}
		GitHubAuthenticationServiceImpl githubServiceImpl = new GitHubAuthenticationService();
		githubServiceImpl.save(gitHubUser);
		return Response.status(200).entity(responseOutput).build();
	}
}
